/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ValoriRouteImport } from './routes/valori'
import { Route as MeetingRouteImport } from './routes/meeting'
import { Route as GalleriaRouteImport } from './routes/galleria'
import { Route as CodroipoCeRouteImport } from './routes/codroipo-ce'
import { Route as BioRouteImport } from './routes/bio'
import { Route as Atletica2000RouteImport } from './routes/atletica-2000'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'

const ValoriRoute = ValoriRouteImport.update({
  id: '/valori',
  path: '/valori',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoute = MeetingRouteImport.update({
  id: '/meeting',
  path: '/meeting',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleriaRoute = GalleriaRouteImport.update({
  id: '/galleria',
  path: '/galleria',
  getParentRoute: () => rootRouteImport,
} as any)
const CodroipoCeRoute = CodroipoCeRouteImport.update({
  id: '/codroipo-ce',
  path: '/codroipo-ce',
  getParentRoute: () => rootRouteImport,
} as any)
const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const Atletica2000Route = Atletica2000RouteImport.update({
  id: '/atletica-2000',
  path: '/atletica-2000',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atletica-2000': typeof Atletica2000Route
  '/bio': typeof BioRoute
  '/codroipo-ce': typeof CodroipoCeRoute
  '/galleria': typeof GalleriaRoute
  '/meeting': typeof MeetingRoute
  '/valori': typeof ValoriRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atletica-2000': typeof Atletica2000Route
  '/bio': typeof BioRoute
  '/codroipo-ce': typeof CodroipoCeRoute
  '/galleria': typeof GalleriaRoute
  '/meeting': typeof MeetingRoute
  '/valori': typeof ValoriRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/atletica-2000': typeof Atletica2000Route
  '/bio': typeof BioRoute
  '/codroipo-ce': typeof CodroipoCeRoute
  '/galleria': typeof GalleriaRoute
  '/meeting': typeof MeetingRoute
  '/valori': typeof ValoriRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/atletica-2000'
    | '/bio'
    | '/codroipo-ce'
    | '/galleria'
    | '/meeting'
    | '/valori'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/atletica-2000'
    | '/bio'
    | '/codroipo-ce'
    | '/galleria'
    | '/meeting'
    | '/valori'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/atletica-2000'
    | '/bio'
    | '/codroipo-ce'
    | '/galleria'
    | '/meeting'
    | '/valori'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  Atletica2000Route: typeof Atletica2000Route
  BioRoute: typeof BioRoute
  CodroipoCeRoute: typeof CodroipoCeRoute
  GalleriaRoute: typeof GalleriaRoute
  MeetingRoute: typeof MeetingRoute
  ValoriRoute: typeof ValoriRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/valori': {
      id: '/valori'
      path: '/valori'
      fullPath: '/valori'
      preLoaderRoute: typeof ValoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting': {
      id: '/meeting'
      path: '/meeting'
      fullPath: '/meeting'
      preLoaderRoute: typeof MeetingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galleria': {
      id: '/galleria'
      path: '/galleria'
      fullPath: '/galleria'
      preLoaderRoute: typeof GalleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codroipo-ce': {
      id: '/codroipo-ce'
      path: '/codroipo-ce'
      fullPath: '/codroipo-ce'
      preLoaderRoute: typeof CodroipoCeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletica-2000': {
      id: '/atletica-2000'
      path: '/atletica-2000'
      fullPath: '/atletica-2000'
      preLoaderRoute: typeof Atletica2000RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  Atletica2000Route: Atletica2000Route,
  BioRoute: BioRoute,
  CodroipoCeRoute: CodroipoCeRoute,
  GalleriaRoute: GalleriaRoute,
  MeetingRoute: MeetingRoute,
  ValoriRoute: ValoriRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
