/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BioRouteImport } from './routes/bio'
import { Route as Atletica2000RouteImport } from './routes/atletica-2000'
import { Route as IndexRouteImport } from './routes/index'

const BioRoute = BioRouteImport.update({
  id: '/bio',
  path: '/bio',
  getParentRoute: () => rootRouteImport,
} as any)
const Atletica2000Route = Atletica2000RouteImport.update({
  id: '/atletica-2000',
  path: '/atletica-2000',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atletica-2000': typeof Atletica2000Route
  '/bio': typeof BioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atletica-2000': typeof Atletica2000Route
  '/bio': typeof BioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atletica-2000': typeof Atletica2000Route
  '/bio': typeof BioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/atletica-2000' | '/bio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/atletica-2000' | '/bio'
  id: '__root__' | '/' | '/atletica-2000' | '/bio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Atletica2000Route: typeof Atletica2000Route
  BioRoute: typeof BioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/bio': {
      id: '/bio'
      path: '/bio'
      fullPath: '/bio'
      preLoaderRoute: typeof BioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atletica-2000': {
      id: '/atletica-2000'
      path: '/atletica-2000'
      fullPath: '/atletica-2000'
      preLoaderRoute: typeof Atletica2000RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Atletica2000Route: Atletica2000Route,
  BioRoute: BioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
